const prisma = require('../config/prisma');
const { generateInvoicePDFBuffer, generateQuotationPDFBuffer } = require('../services/pdfService');

/**
 * Endpoint to download an Invoice PDF generated by React PDF
 */
const downloadInvoicePDF = async (req, res, next) => {
  try {
    const { id } = req.params;
    console.log(`🖨️ [React PDF Engine] Generating Invoice PDF for id: ${id}`);
    const invoice = await prisma.invoice.findUnique({
      where: { id },
      include: {
        client: true,
        financialYear: true,
        items: true
      }
    });

    if (!invoice) {
      return res.status(404).json({ error: 'Invoice not found' });
    }

    const company = await prisma.companyDetails.findFirst();
    const pdfBuffer = await generateInvoicePDFBuffer(invoice, company);

    const safeFilename = `Invoice_${invoice.invoiceNumber.replace(/[\/\\]/g, '_')}.pdf`;
    console.log(`✅ [React PDF Engine] Invoice PDF generated successfully (${pdfBuffer.length} bytes)`);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${safeFilename}"`);
    res.setHeader('Content-Length', pdfBuffer.length);
    res.send(pdfBuffer);
  } catch (error) {
    console.error('❌ [React PDF Engine] Failed to generate invoice PDF:', error);
    next(error);
  }
};

/**
 * Endpoint to download a Quotation PDF generated by React PDF
 */
const downloadQuotationPDF = async (req, res, next) => {
  try {
    const { id } = req.params;
    console.log(`🖨️ [React PDF Engine] Generating Quotation PDF for id: ${id}`);
    const quotation = await prisma.quotation.findUnique({
      where: { id },
      include: {
        client: true,
        items: true
      }
    });

    if (!quotation) {
      return res.status(404).json({ error: 'Quotation not found' });
    }

    const company = await prisma.companyDetails.findFirst();
    const pdfBuffer = await generateQuotationPDFBuffer(quotation, company);

    const safeFilename = `Quotation_${quotation.quotationNumber.replace(/[\/\\]/g, '_')}.pdf`;
    console.log(`✅ [React PDF Engine] Quotation PDF generated successfully (${pdfBuffer.length} bytes)`);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${safeFilename}"`);
    res.setHeader('Content-Length', pdfBuffer.length);
    res.send(pdfBuffer);
  } catch (error) {
    console.error('❌ [React PDF Engine] Failed to generate quotation PDF:', error);
    next(error);
  }
};

/**
 * Endpoint to render custom PDF via React PDF engine
 */
const renderCustomPDF = async (req, res, next) => {
  try {
    const { invoiceId, quotationId, filename = 'document.pdf' } = req.body;

    if (invoiceId) {
      req.params = { id: invoiceId };
      return downloadInvoicePDF(req, res, next);
    }
    if (quotationId) {
      req.params = { id: quotationId };
      return downloadQuotationPDF(req, res, next);
    }

    return res.status(400).json({ error: 'Document ID (invoiceId or quotationId) is required for PDF generation.' });
  } catch (error) {
    console.error('❌ [React PDF Engine] Failed to render custom PDF:', error);
    next(error);
  }
};

module.exports = {
  downloadInvoicePDF,
  downloadQuotationPDF,
  renderCustomPDF
};
